# Generated by Django 3.2.6 on 2021-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=100)),
            ],
        ),
    ]
