# Generated by Django 3.2.6 on 2021-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_post_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='qna_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('answr', models.CharField(max_length=1000)),
                ('auser', models.CharField(max_length=100)),
            ],
        ),
    ]
